package com.entity;
// Generated 2017-4-28 9:10:52 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Brand generated by hbm2java
 */
@Entity
@Table(name = "brand", catalog = "shop")
public class Brand implements java.io.Serializable {

    private Integer brandId;
    private String brandName;
    private Set<Light> lights = new HashSet<Light>(0);

    public Brand() {
    }

    public Brand(String brandName) {
        this.brandName = brandName;
    }

    public Brand(String brandName, Set<Light> lights) {
        this.brandName = brandName;
        this.lights = lights;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "BrandId", unique = true, nullable = false)
    public Integer getBrandId() {
        return this.brandId;
    }

    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    @Column(name = "BrandName", nullable = false, length = 20)
    public String getBrandName() {
        return this.brandName;
    }

    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "brand")
    public Set<Light> getLights() {
        return this.lights;
    }

    public void setLights(Set<Light> lights) {
        this.lights = lights;
    }

}
