package com.entity;
// Generated 2017-4-28 9:10:52 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Catagory generated by hbm2java
 */
@Entity
@Table(name = "catagory", catalog = "shop")
public class Catagory implements java.io.Serializable {

    private Integer catagoryId;
    private String catagoryName;
    private Set<Light> lights = new HashSet<Light>(0);

    public Catagory() {
    }

    public Catagory(String catagoryName) {
        this.catagoryName = catagoryName;
    }

    public Catagory(String catagoryName, Set<Light> lights) {
        this.catagoryName = catagoryName;
        this.lights = lights;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "CatagoryId", unique = true, nullable = false)
    public Integer getCatagoryId() {
        return this.catagoryId;
    }

    public void setCatagoryId(Integer catagoryId) {
        this.catagoryId = catagoryId;
    }

    @Column(name = "CatagoryName", nullable = false, length = 20)
    public String getCatagoryName() {
        return this.catagoryName;
    }

    public void setCatagoryName(String catagoryName) {
        this.catagoryName = catagoryName;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "catagory")
    public Set<Light> getLights() {
        return this.lights;
    }

    public void setLights(Set<Light> lights) {
        this.lights = lights;
    }

}
