package com.entity;
// Generated 2017-4-28 9:10:52 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Comments generated by hbm2java
 */
@Entity
@Table(name = "comments", catalog = "shop")
public class Comments implements java.io.Serializable {

    private Integer commentsId;
    private Light light;
    private User user;
    private String comments;
    private Date date;

    public Comments() {
    }

    public Comments(Light light, User user, String comments, Date date) {
        this.light = light;
        this.user = user;
        this.comments = comments;
        this.date = date;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "CommentsId", unique = true, nullable = false)
    public Integer getCommentsId() {
        return this.commentsId;
    }

    public void setCommentsId(Integer commentsId) {
        this.commentsId = commentsId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "LightId", nullable = false)
    public Light getLight() {
        return this.light;
    }

    public void setLight(Light light) {
        this.light = light;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "UserId", nullable = false)
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @Column(name = "Comments", nullable = false, length = 150)
    public String getComments() {
        return this.comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Date", nullable = false, length = 19)
    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

}
