package com.entity;
// Generated 2017-4-28 9:10:52 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Light generated by hbm2java
 */
@Entity
@Table(name = "light", catalog = "shop")
public class Light implements java.io.Serializable {

    private Integer lightId;
    private Stryle stryle;
    private Catagory catagory;
    private Brand brand;
    private String stuff;
    private String color;
    private String locate;
    private long price;
    private int quantity;
    private String description;
    private String images;
    private Set<Comments> commentses = new HashSet<Comments>(0);
    private Set<Orders> orderses = new HashSet<Orders>(0);
    private Set<Wishlist> wishlists = new HashSet<Wishlist>(0);
    private Set<Myshopcart> myshopcarts = new HashSet<Myshopcart>(0);

    public Light() {
    }

    public Light(Stryle stryle, Catagory catagory, Brand brand, long price, int quantity) {
        this.stryle = stryle;
        this.catagory = catagory;
        this.brand = brand;
        this.price = price;
        this.quantity = quantity;
    }

    public Light(Stryle stryle, Catagory catagory, Brand brand, String stuff, String color, String locate, long price,
                 int quantity, String description, String images, Set<Comments> commentses, Set<Orders> orderses,
                 Set<Wishlist> wishlists, Set<Myshopcart> myshopcarts) {
        this.stryle = stryle;
        this.catagory = catagory;
        this.brand = brand;
        this.stuff = stuff;
        this.color = color;
        this.locate = locate;
        this.price = price;
        this.quantity = quantity;
        this.description = description;
        this.images = images;
        this.commentses = commentses;
        this.orderses = orderses;
        this.wishlists = wishlists;
        this.myshopcarts = myshopcarts;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "LightId", unique = true, nullable = false)
    public Integer getLightId() {
        return this.lightId;
    }

    public void setLightId(Integer lightId) {
        this.lightId = lightId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "StyleId", nullable = false)
    public Stryle getStryle() {
        return this.stryle;
    }

    public void setStryle(Stryle stryle) {
        this.stryle = stryle;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CatagoryId", nullable = false)
    public Catagory getCatagory() {
        return this.catagory;
    }

    public void setCatagory(Catagory catagory) {
        this.catagory = catagory;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "BrandId", nullable = false)
    public Brand getBrand() {
        return this.brand;
    }

    public void setBrand(Brand brand) {
        this.brand = brand;
    }

    @Column(name = "Stuff", length = 20)
    public String getStuff() {
        return this.stuff;
    }

    public void setStuff(String stuff) {
        this.stuff = stuff;
    }

    @Column(name = "Color", length = 20)
    public String getColor() {
        return this.color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    @Column(name = "Locate", length = 20)
    public String getLocate() {
        return this.locate;
    }

    public void setLocate(String locate) {
        this.locate = locate;
    }

    @Column(name = "Price", nullable = false, precision = 18, scale = 0)
    public long getPrice() {
        return this.price;
    }

    public void setPrice(long price) {
        this.price = price;
    }

    @Column(name = "Quantity", nullable = false)
    public int getQuantity() {
        return this.quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    @Column(name = "Description", length = 250)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "Images", length = 50)
    public String getImages() {
        return this.images;
    }

    public void setImages(String images) {
        this.images = images;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "light")
    public Set<Comments> getCommentses() {
        return this.commentses;
    }

    public void setCommentses(Set<Comments> commentses) {
        this.commentses = commentses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "light")
    public Set<Orders> getOrderses() {
        return this.orderses;
    }

    public void setOrderses(Set<Orders> orderses) {
        this.orderses = orderses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "light")
    public Set<Wishlist> getWishlists() {
        return this.wishlists;
    }

    public void setWishlists(Set<Wishlist> wishlists) {
        this.wishlists = wishlists;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "light")
    public Set<Myshopcart> getMyshopcarts() {
        return this.myshopcarts;
    }

    public void setMyshopcarts(Set<Myshopcart> myshopcarts) {
        this.myshopcarts = myshopcarts;
    }

}
