package com.entity;
// Generated 2017-4-28 9:10:52 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name = "orders", catalog = "shop")
public class Orders implements java.io.Serializable {

    private Integer ordersId;
    private Light light;
    private User user;
    private int quantity;
    private long totalPrice;
    private Date date;
    private int orderStateId;
    private int showOrNot;
    private String receiveName;
    private String receivePhone;
    private String address;
    private String email;
    private String postalCode;
    private String postType;
    private String paymentType;
    private int postFee;

    public Orders() {
    }

    public Orders(Light light, User user, int quantity, long totalPrice, Date date, int orderStateId, int showOrNot,
                  String receiveName, String receivePhone, String address, String postType, int postFee) {
        this.light = light;
        this.user = user;
        this.quantity = quantity;
        this.totalPrice = totalPrice;
        this.date = date;
        this.orderStateId = orderStateId;
        this.showOrNot = showOrNot;
        this.receiveName = receiveName;
        this.receivePhone = receivePhone;
        this.address = address;
        this.postType = postType;
        this.postFee = postFee;
    }

    public Orders(Light light, User user, int quantity, long totalPrice, Date date, int orderStateId, int showOrNot,
                  String receiveName, String receivePhone, String address, String email, String postalCode, String postType,
                  String paymentType, int postFee) {
        this.light = light;
        this.user = user;
        this.quantity = quantity;
        this.totalPrice = totalPrice;
        this.date = date;
        this.orderStateId = orderStateId;
        this.showOrNot = showOrNot;
        this.receiveName = receiveName;
        this.receivePhone = receivePhone;
        this.address = address;
        this.email = email;
        this.postalCode = postalCode;
        this.postType = postType;
        this.paymentType = paymentType;
        this.postFee = postFee;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "OrdersId", unique = true, nullable = false)
    public Integer getOrdersId() {
        return this.ordersId;
    }

    public void setOrdersId(Integer ordersId) {
        this.ordersId = ordersId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "LightId", nullable = false)
    public Light getLight() {
        return this.light;
    }

    public void setLight(Light light) {
        this.light = light;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "UserId", nullable = false)
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @Column(name = "Quantity", nullable = false)
    public int getQuantity() {
        return this.quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    @Column(name = "TotalPrice", nullable = false, precision = 18, scale = 0)
    public long getTotalPrice() {
        return this.totalPrice;
    }

    public void setTotalPrice(long totalPrice) {
        this.totalPrice = totalPrice;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Date", nullable = false, length = 19)
    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    @Column(name = "OrderStateId", nullable = false)
    public int getOrderStateId() {
        return this.orderStateId;
    }

    public void setOrderStateId(int orderStateId) {
        this.orderStateId = orderStateId;
    }

    @Column(name = "ShowOrNot", nullable = false)
    public int getShowOrNot() {
        return this.showOrNot;
    }

    public void setShowOrNot(int showOrNot) {
        this.showOrNot = showOrNot;
    }

    @Column(name = "ReceiveName", nullable = false, length = 20)
    public String getReceiveName() {
        return this.receiveName;
    }

    public void setReceiveName(String receiveName) {
        this.receiveName = receiveName;
    }

    @Column(name = "ReceivePhone", nullable = false, length = 11)
    public String getReceivePhone() {
        return this.receivePhone;
    }

    public void setReceivePhone(String receivePhone) {
        this.receivePhone = receivePhone;
    }

    @Column(name = "Address", nullable = false, length = 50)
    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Column(name = "Email", length = 50)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "PostalCode", length = 6)
    public String getPostalCode() {
        return this.postalCode;
    }

    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    @Column(name = "PostType", nullable = false, length = 20)
    public String getPostType() {
        return this.postType;
    }

    public void setPostType(String postType) {
        this.postType = postType;
    }

    @Column(name = "PaymentType", length = 20)
    public String getPaymentType() {
        return this.paymentType;
    }

    public void setPaymentType(String paymentType) {
        this.paymentType = paymentType;
    }

    @Column(name = "PostFee", nullable = false)
    public int getPostFee() {
        return this.postFee;
    }

    public void setPostFee(int postFee) {
        this.postFee = postFee;
    }

}
