package com.entity;
// Generated 2017-4-28 9:10:52 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Statistics generated by hbm2java
 */
@Entity
@Table(name = "statistics", catalog = "shop")
public class Statistics implements java.io.Serializable {

    private int lightId;
    private int clicks;
    private int storeCount;
    private int stateCount;

    public Statistics() {
    }

    public Statistics(int lightId, int clicks, int storeCount, int stateCount) {
        this.lightId = lightId;
        this.clicks = clicks;
        this.storeCount = storeCount;
        this.stateCount = stateCount;
    }

    @Id

    @Column(name = "LightId", unique = true, nullable = false)
    public int getLightId() {
        return this.lightId;
    }

    public void setLightId(int lightId) {
        this.lightId = lightId;
    }

    @Column(name = "Clicks", nullable = false)
    public int getClicks() {
        return this.clicks;
    }

    public void setClicks(int clicks) {
        this.clicks = clicks;
    }

    @Column(name = "StoreCount", nullable = false)
    public int getStoreCount() {
        return this.storeCount;
    }

    public void setStoreCount(int storeCount) {
        this.storeCount = storeCount;
    }

    @Column(name = "StateCount", nullable = false)
    public int getStateCount() {
        return this.stateCount;
    }

    public void setStateCount(int stateCount) {
        this.stateCount = stateCount;
    }

}
