package com.entity;
// Generated 2017-4-28 9:10:52 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Stryle generated by hbm2java
 */
@Entity
@Table(name = "stryle", catalog = "shop")
public class Stryle implements java.io.Serializable {

    private Integer styleId;
    private String styleName;
    private Set<Light> lights = new HashSet<Light>(0);

    public Stryle() {
    }

    public Stryle(String styleName) {
        this.styleName = styleName;
    }

    public Stryle(String styleName, Set<Light> lights) {
        this.styleName = styleName;
        this.lights = lights;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "StyleId", unique = true, nullable = false)
    public Integer getStyleId() {
        return this.styleId;
    }

    public void setStyleId(Integer styleId) {
        this.styleId = styleId;
    }

    @Column(name = "StyleName", nullable = false, length = 20)
    public String getStyleName() {
        return this.styleName;
    }

    public void setStyleName(String styleName) {
        this.styleName = styleName;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "stryle")
    public Set<Light> getLights() {
        return this.lights;
    }

    public void setLights(Set<Light> lights) {
        this.lights = lights;
    }

}
