package com.entity;
// Generated 2017-4-28 9:10:52 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "shop")
public class User implements java.io.Serializable {

    private Integer userId;
    private Userroles userroles;
    private Userstates userstates;
    private String userName;
    private String address;
    private String postalCode;
    private String phone;
    private String email;
    private String gender;
    private String loginId;
    private String loginPwd;
    private Date lastLoginTime;
    private Set<Comments> commentses = new HashSet<Comments>(0);
    private Set<Orders> orderses = new HashSet<Orders>(0);
    private Set<Wishlist> wishlists = new HashSet<Wishlist>(0);
    private Set<Myshopcart> myshopcarts = new HashSet<Myshopcart>(0);

    public User() {
    }

    public User(Userroles userroles, Userstates userstates, String userName, String phone, String gender,
                String loginId, String loginPwd) {
        this.userroles = userroles;
        this.userstates = userstates;
        this.userName = userName;
        this.phone = phone;
        this.gender = gender;
        this.loginId = loginId;
        this.loginPwd = loginPwd;
    }

    public User(Userroles userroles, Userstates userstates, String userName, String address, String postalCode,
                String phone, String email, String gender, String loginId, String loginPwd, Date lastLoginTime,
                Set<Comments> commentses, Set<Orders> orderses, Set<Wishlist> wishlists, Set<Myshopcart> myshopcarts) {
        this.userroles = userroles;
        this.userstates = userstates;
        this.userName = userName;
        this.address = address;
        this.postalCode = postalCode;
        this.phone = phone;
        this.email = email;
        this.gender = gender;
        this.loginId = loginId;
        this.loginPwd = loginPwd;
        this.lastLoginTime = lastLoginTime;
        this.commentses = commentses;
        this.orderses = orderses;
        this.wishlists = wishlists;
        this.myshopcarts = myshopcarts;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "UserId", unique = true, nullable = false)
    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "UserRoleId", nullable = false)
    public Userroles getUserroles() {
        return this.userroles;
    }

    public void setUserroles(Userroles userroles) {
        this.userroles = userroles;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "UserStateId", nullable = false)
    public Userstates getUserstates() {
        return this.userstates;
    }

    public void setUserstates(Userstates userstates) {
        this.userstates = userstates;
    }

    @Column(name = "UserName", nullable = false, length = 20)
    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    @Column(name = "Address", length = 50)
    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Column(name = "PostalCode", length = 6)
    public String getPostalCode() {
        return this.postalCode;
    }

    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    @Column(name = "Phone", nullable = false, length = 11)
    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Column(name = "Email", length = 50)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "Gender", nullable = false, length = 4)
    public String getGender() {
        return this.gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    @Column(name = "LoginId", nullable = false, length = 50)
    public String getLoginId() {
        return this.loginId;
    }

    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }

    @Column(name = "LoginPwd", nullable = false, length = 50)
    public String getLoginPwd() {
        return this.loginPwd;
    }

    public void setLoginPwd(String loginPwd) {
        this.loginPwd = loginPwd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LastLoginTime", length = 19)
    public Date getLastLoginTime() {
        return this.lastLoginTime;
    }

    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
    public Set<Comments> getCommentses() {
        return this.commentses;
    }

    public void setCommentses(Set<Comments> commentses) {
        this.commentses = commentses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
    public Set<Orders> getOrderses() {
        return this.orderses;
    }

    public void setOrderses(Set<Orders> orderses) {
        this.orderses = orderses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
    public Set<Wishlist> getWishlists() {
        return this.wishlists;
    }

    public void setWishlists(Set<Wishlist> wishlists) {
        this.wishlists = wishlists;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
    public Set<Myshopcart> getMyshopcarts() {
        return this.myshopcarts;
    }

    public void setMyshopcarts(Set<Myshopcart> myshopcarts) {
        this.myshopcarts = myshopcarts;
    }

}
