package com.entity;
// Generated 2017-4-28 9:10:52 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Userstates generated by hbm2java
 */
@Entity
@Table(name = "userstates", catalog = "shop")
public class Userstates implements java.io.Serializable {

    private Integer id;
    private String nmae;
    private Set<User> users = new HashSet<User>(0);

    public Userstates() {
    }

    public Userstates(String nmae) {
        this.nmae = nmae;
    }

    public Userstates(String nmae, Set<User> users) {
        this.nmae = nmae;
        this.users = users;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "Id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "Nmae", nullable = false, length = 20)
    public String getNmae() {
        return this.nmae;
    }

    public void setNmae(String nmae) {
        this.nmae = nmae;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "userstates")
    public Set<User> getUsers() {
        return this.users;
    }

    public void setUsers(Set<User> users) {
        this.users = users;
    }

}
