package com.entity;
// Generated 2017-4-28 9:10:52 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Wishlist generated by hbm2java
 */
@Entity
@Table(name = "wishlist", catalog = "shop")
public class Wishlist implements java.io.Serializable {

    private Integer wishListId;
    private Light light;
    private User user;
    private Date storeDate;

    public Wishlist() {
    }

    public Wishlist(Light light, User user, Date storeDate) {
        this.light = light;
        this.user = user;
        this.storeDate = storeDate;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "WishListId", unique = true, nullable = false)
    public Integer getWishListId() {
        return this.wishListId;
    }

    public void setWishListId(Integer wishListId) {
        this.wishListId = wishListId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "LightId", nullable = false)
    public Light getLight() {
        return this.light;
    }

    public void setLight(Light light) {
        this.light = light;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "UserId", nullable = false)
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "StoreDate", nullable = false, length = 19)
    public Date getStoreDate() {
        return this.storeDate;
    }

    public void setStoreDate(Date storeDate) {
        this.storeDate = storeDate;
    }

}
